root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "tmp/app"
cmd = "CGO_ENABLED=0 go build -o tmp/app ./cmd/collect/main.go"
exclude_dir = ["tmp", "testdata"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
include_ext = ["go", "tpl", "tmpl", "html"]
stop_on_error = true

[misc]
clean_on_exit = true